### ISSUE TITLE
volumetric shaders

### ISSUE THREAD

**Issue by OmidGhotbi** [LuisaGroup/LuisaCompute#178]
is there any documentation about Luisa shaders and does it support and volumetric shaders for smoke, fire and cloud for an example?

**Comment by Mike-Leo-Smith** [comment]
Sorry, currently we do not have a doc, and volumetric rendering is not implemented.

**Comment by OmidGhotbi** [comment]
Thank you for your response. I like to know if this is possible to ask for support for volumetric shaders for the future as new features.
If not I would appreciate it if you could point me to how I can write a shader so I may be able to help add a volumetric shader to Luisa. I have experience with Luxcore render which may come in handy here.
I need more information about Luisa's shaders and how the core calculates the shaders so I can add the necessary part to the core if it needed.

**Comment by xiaomx32** [comment]
Dear @OmidGhotbi
I have been learning LuisaCompute recently and would like to share some of my thoughts, which might be helpful to you. The lack of documentation can indeed be confusing for beginners, but fortunately, the project includes a variety of [examples](https://github.com/LuisaGroup/LuisaCompute/tree/next/src/tests) that demonstrate how to use shaders. Of course, don’t miss the [LuisaRender](https://github.com/LuisaGroup/LuisaRender) project either.
Additionally, if you are interested, I would greatly appreciate your guidance on this [repository](https://github.com/Learning-Ray-Tracing-From-Zero/luisa_compute_examples), it's a collection of LC examples that I maintain separately. As I am still learning LC, these examples are much cruder than the official ones, and hope they might be more suitable for beginners.

**Comment by Mike-Leo-Smith** [comment]
Thank you very much for being willing to help!

> I like to know if this is possible to ask for support for volumetric shaders for the future as new features.

Yes, it's very welcome! You can open an issue under the LuisaRender repo. Though I might not have the time recently, one of my labmates might be interested in implementing volumetric rendering after the SIGGRAPH Asia 2025 submission.


> I need more information about Luisa's shaders and how the core calculates the shaders so I can add the necessary part to the core if it needed.

Currently, the surface shaders are derived from a base class `Surface` defined in https://github.com/LuisaGroup/LuisaRender/blob/next/src/base/surface.h. There are some main components:
- `Surface` itself is a scene node that just records properties from the scene definition file.
- `Surface::build()` generates a `Surface::Instance`, which creates resources like textures or LUTs on the GPU.
- During rendering, `Surface::Instance::closure()` evaluates textures and other shader parameters and generates a `Surface::Closure`.
- `Surface::Closure` can be used to evaluate the BSDF for a pair of input/output directions and sample for a now incoming direction.

All derived shaders are implemented under https://github.com/LuisaGroup/LuisaRender/tree/next/src/surfaces and `matte.cpp` might be a good starting point for you to understand how to write a surface shader.

For volumetric shaders, we currently do not have a specific design but I guess it should be much like the surface shaders.

**Comment by OmidGhotbi** [comment]
@xiaomx32 @Mike-Leo-Smith
Thank you so much for both kind and helpful instructions, I will create a feature request and at the same time, I'll try to investigate more in the implementation of volumetric shaders in LC. it can take a while as i am new in LC. By the way, I am impressed by the LC and i intend to integrate Luisa Compute into the TAngra multi-physics engine.
I used LuxCore to start with but the lack of updates and the complexity of the GPL 3 license make it a less obvious choice.
I hope i will be able to help in that part as I can see Genesis also used LC and with any physics solver sooner or later volumetric is a must.

**Comment by Mike-Leo-Smith** [comment]
> [@xiaomx32](https://github.com/xiaomx32) [@Mike-Leo-Smith](https://github.com/Mike-Leo-Smith) Thank you so much for both kind and helpful instructions, I will create a feature request and at the same time, I'll try to investigate more in the implementation of volumetric shaders in LC. it can take a while as i am new in LC. By the way, I am impressed by the LC and i intend to integrate Luisa Compute into the TAngra multi-physics engine. I used LuxCore to start with but the lack of updates and the complexity of the GPL 3 license make it a less obvious choice. I hope i will be able to help in that part as I can see Genesis also used LC and with any physics solver sooner or later volumetric is a must.

Thank you for the info and help. We'll keep working to make Luisa better!

**Comment by OmidGhotbi** [comment]
I have a few questions regarding volumetric shader implementation. i created 2 basic volume shaders, and when I add them to the scene, they both will always return black. My question is, are there any parameters in the renderer itself that need to be activated, or perhaps any parameters regarding the number of bounce lights in transparent/volume objects in LC?
Based on other types of transmit shaders like glass or translucent LC should be capable of doing volumetric without any change in core ad just by defining the Volume shaders. please correct me if I'm wrong.
I`m rendering one of the samples using CUDA for testing with no errors.

![Image](https://github.com/user-attachments/assets/12e47544-874a-4ad1-bd02-c641dceff90f)

**Comment by Mike-Leo-Smith** [comment]
Hi, @OmidGhotbi 

Thank you for the attempt. Could you provide some details on the changes you've made to the codebase and the scene configuration of the rendering?

**Comment by OmidGhotbi** [comment]
> Hi, [@OmidGhotbi](https://github.com/OmidGhotbi)
> 
> Thank you for the attempt. Could you provide some details on the changes you've made to the codebase and the scene configuration of the rendering?

Before going in detail, can I ask you about LuisaRender\src\media\homogeneous.cpp and any usage example?
Is there any sample scene to show how it works?
i presume it is a kind of environment volume and needs to be created like this:
Medium med_Fog : Homogeneous {
  eta { 0.1 }
  sigma_a : Constant { v { 0.1, 0.1, 0.1 } }
  sigma_s : Constant { v { 0.5, 0.5, 0.5 } }
  phasefunction : HenyeyGreenstein {
    g { -0.3872983346207417 }
  }
}
Then set it as medium for environment_medium or perhaps shader medium.
But I am not sure and I did not find any document or example about it.

**Comment by Mike-Leo-Smith** [comment]
Hi, @OmidGhotbi 

Sorry, but `LuisaRender\src\media\homogeneous.cpp` is unfinished and does not work with the integrators. So I guess that's why the ball was rendered black.

**Comment by OmidGhotbi** [comment]
> Hi, [@OmidGhotbi](https://github.com/OmidGhotbi)
> 
> Sorry, but `LuisaRender\src\media\homogeneous.cpp` is unfinished and does not work with the integrators. So I guess that's why the ball was rendered black.

Oh I see.
From the code  (integrator.h / integrator.cpp and ProgressiveIntegrator), there is no volume‐sampling logic yet. All code it has is a base integrator class plus a skeleton “progressive” integrator that calls Li(...) inside a render loop.  same in mega_path.cpp t only does surface‐based path tracing with no calls to medium sampling, no distance sampling, no phase functions, etc.
You even note that:
```
Float3 ProgressiveIntegrator::Instance::Li(...) const noexcept {
    LUISA_ERROR_WITH_LOCATION("ProgressiveIntegrator::Li() is not implemented.");
}
```

So, that means the path‐tracing logic (which actually marches through surfaces and volumes) is missing. And first, I need to implement that.
I will try that and get back to you.
Thank you.

**Comment by OmidGhotbi** [comment]
Well, I'm starting to get somewhere.
It's not correct yet, but it shows it can calculate the basic ray path and ray depth inside the volume. 😂 First step, I really wish I could have information or experience on LC. i will try my best.

![Image](https://github.com/user-attachments/assets/a44e83e7-c3b1-46c6-86f3-79a2ccd1ba4f)

**Comment by OmidGhotbi** [comment]
I almost made it work. i upgraded the volume question, russian roulette, depth trace, and color calculation in MegaPath.
Here a few quick examples.

![Image](https://github.com/user-attachments/assets/7c5e27b3-156c-482d-b039-136bc15b234f)

new volume calculation:
![Image](https://github.com/user-attachments/assets/4fc1615f-4a43-4353-b671-0992fc57f868)

Before changing the code- original state:
![Image](https://github.com/user-attachments/assets/d3835c2a-f1e9-4645-aa43-47181e6de621)

I have one question before I go to the next part and add volume for close meshes and VDB. I noticed that sometimes, for some scenes, the render will get stuck for a long time on the Starting Render Phase. Do you have any idea about it? I can not see any particular errors with it.

![Image](https://github.com/user-attachments/assets/0c4cc908-efb8-4626-84cc-22d64e823ea4)

Should I create a fork and create a pull request for contribution, or are there any special rules that I need to follow?

**Comment by Mike-Leo-Smith** [comment]
Wow, thank you so much and the results are very cool! A pull request is very welcome and appreciated!

> I noticed that sometimes, for some scenes, the render will get stuck for a long time on the Starting Render Phase. Do you have any idea about it? I can not see any particular errors with it.

I think it’s likely the shader compilation time. Luisa uses JIT that generates shader code at runtime and compile it dynamically. For a complex shader it can take considerable time (like some seconds to a minute). We are currently working hard on the LuisaCompute side to cut down this time.

Other unexpected issues might also be possible. I’m very willing to help check if anything else goes wrong when you pull request.

Thank you again for contributing!

**Comment by OmidGhotbi** [comment]
After i fix the issue with ray angle a long side of camera that cause stuck on render on rare case for example extreme field of view or mixing aperture and filed of view. i start pushing the code that is stable now on my GitHub fork repo.
I will test it a few more times and be sure about other issues, then I will ask to pull the code on the LC repo.
By the way, having fog and volume can scatter the light in the scene and I notice changing aperture will not affect the brightness or light volume. 
1- Is it the normal behavior in LC, or I making a mistake?
2- Is there any exposure controller that I can use to change Gamma, Brightness, etc?
3- Does it make sense to add an option for cut out near or far fog in the scene?
no exposure:
![Image](https://github.com/user-attachments/assets/5ae5ad67-777b-41e1-a1e7-ce33a509aff9)

with -0.76 exposure in Photoshop
![Image](https://github.com/user-attachments/assets/2937c178-8ab7-4223-a8a4-1563da20cf77)

another field of view and aperture:
I hope you like it.
![Image](https://github.com/user-attachments/assets/2614e5c7-23c9-43c3-862a-3e5781575e3f)

**Comment by Mike-Leo-Smith** [comment]
Hi, @OmidGhotbi 

Very excited to see these beautiful results and thank you so much for your efforts!

Here are my answers to your questions:

> I notice changing aperture will not affect the brightness or light volume.
> 1- Is it the normal behavior in LC, or I making a mistake?

Yes, this is the expected behavior by design. The aperture parameter of the thin-lens camera only affects depth of field, not exposure.

> 2- Is there any exposure controller that I can use to change Gamma, Brightness, etc?

Currently, the Color film supports setting exposure as shown below:
```JSON
"film": {
    "impl": "Color",
    "prop": {
        /* other properties */
        "exposure": -0.76 // or a per-channel list like [-0.76, -0.76, -0.76]
    }
},
```
The output is always in linear sRGB. That said, it should be relatively straightforward to add more image controls or tone mapping options, similar to what's implemented in the [Display](https://github.com/LuisaGroup/LuisaRender/blob/next/src/films/display.cpp) film.

> 3- Does it make sense to add an option for cut out near or far fog in the scene?

Yes, I think it definitely makes sense. It would give users more control and might also reduce some computation.

Cheers!

**Comment by OmidGhotbi** [comment]
Sorry for the delay, I was a bit busy with a few health-related matters. i checked the code last night again and pushed it on GitHub, Also, I created a pull request for it in LuisaRenderer Repo.
Where should I upload the test scene for a usage example? i need to mention, they are simple scenes to show the usage. Maybe a VolumeTestScene branch in https://github.com/LuisaGroup/LuisaRenderScenes so after finishing the final code and test I can replace them with a more advanced scene.
Here are a few test scenes https://github.com/OmidGhotbi/LuisaRenderScenes/releases/tag/v0.1
I tested the code on Windows only.

**Comment by OmidGhotbi** [comment]
i also in the middle of the development of the LuisaRenderer plugin for Tangra and the Luisa Blender addon.
Here is the first test. https://youtu.be/VrtXvZPHDUU I saved each frame as a static mesh, then rendered it. I hope you like it.

**Comment by Mike-Leo-Smith** [comment]
> Sorry for the delay, I was a bit busy with a few health-related matters. i checked the code last night again and pushed it on GitHub, Also, I created a pull request for it in LuisaRenderer Repo.

Please take care! I’ve merged the PR — it looks great. Thank you very much!

> Where should I upload the test scene for a usage example? i need to mention, they are simple scenes to show the usage. Maybe a VolumeTestScene branch in https://github.com/LuisaGroup/LuisaRenderScenes so after finishing the final code and test I can replace them with a more advanced scene. Here are a few test scenes https://github.com/OmidGhotbi/LuisaRenderScenes/releases/tag/v0.1 I tested the code on Windows only.

I think it's totally fine to push the scenes directly to the [LuisaRenderScenes](https://github.com/LuisaGroup/LuisaRenderScenes) repo. Even simple scenes can be helpful, especially for graphics researchers.

**Comment by Mike-Leo-Smith** [comment]
> i also in the middle of the development of the LuisaRenderer plugin for Tangra and the Luisa Blender addon. Here is the first test. https://youtu.be/VrtXvZPHDUU I saved each frame as a static mesh, then rendered it. I hope you like it.

Thanks for sharing. The test looks very cool, and it's exciting to see LuisaRender integrated into Tangra. Looking forward to seeing how the plugin and addon evolve!

**Comment by Mike-Leo-Smith** [comment]
> I tested the code on Windows only.

I have tested the code and scenes on Linux and they worked smoothly. I also pushed a small commit in LuisaRender to enable `device_log` only in debug builds to avoid the printing overhead.

**Comment by OmidGhotbi** [comment]
> > I tested the code on Windows only.
> 
> I have tested the code and scenes on Linux and they worked smoothly. I also pushed a small commit in LuisaRender to enable `device_log` only in debug builds to avoid the printing overhead.

This is great because I noticed in RTX 5080 the render time was higher than 3070, despite the GPU finishing the job faster, debug information was still floating in the terminal waiting to be finished. I'm still not sure it is 100% related to the console debug message, but I assume it adds up.

I did change the camera base a bit to avoid the epsilon angle issue for all rendered frames, Please feel free to report any problem regarding this change in other renderers or camera behavior.

I will try to add support for heterogeneous volumes next week.

i also see a macOS build issue in the repo! Should I take a look at it, or is it just github action issue?

One question, even I when I use cmake -S . -B build -D CMAKE_BUILD_TYPE=Release. After building, it will always build the debug version. Should I do anything else?

**Comment by Mike-Leo-Smith** [comment]
> i also see a macOS build issue in the repo! Should I take a look at it, or is it just github action issue?

No worries, I'll handle it.

> One question, even I when I use cmake -S . -B build -D CMAKE_BUILD_TYPE=Release. After building, it will always build the debug version. Should I do anything else?

This is strange. Did you try deleting the build folder and rebuilding?

**Comment by OmidGhotbi** [comment]
> This is strange. Did you try deleting the build folder and rebuilding?

I will create a clean VM all the time, and even the first try was like that. Also, yes, I removed the build folder too for the next try, maybe the Visual Studio version caused this, or Cuda 12.8.1 that I replaced. I'm not sure.

**Comment by Mike-Leo-Smith** [comment]
> I will create a clean VM all the time, and even the first try was like that. Also, yes, I removed the build folder too for the next try, maybe the Visual Studio version caused this, or Cuda 12.8.1 that I replaced. I'm not sure.

If you are using Visual Studio to open the CMake directory, you might need to follow https://learn.microsoft.com/en-us/cpp/build/customize-cmake-settings to create a new custom configuration for release build.

**Comment by OmidGhotbi** [comment]
> > I will create a clean VM all the time, and even the first try was like that. Also, yes, I removed the build folder too for the next try, maybe the Visual Studio version caused this, or Cuda 12.8.1 that I replaced. I'm not sure.
> 
> If you are using Visual Studio to open the CMake directory, you might need to follow https://learn.microsoft.com/en-us/cpp/build/customize-cmake-settings to create a new custom configuration for release build.

I'm building with in powershell using vsbuild tools. shooul I create another config?
build steps in powershel:
C:\LuisaRender> cmake -S . -B build -D CMAKE_BUILD_TYPE=Release
C:\LuisaRender> cmake --build build

Windows 11
Cuda 12.8.1
Visual Studio 2022
MSBuild version 17.12.12+1cce77968 for .NET Framework 17.12.12.57101
CMake version 3.31.4


To be sure, I also tested in Visual Studio IDE, and the project settings were set to debug. Of course, I can change it to release and build the project, but every time I need to open the solution in the IDE and change the settings.

**Comment by Mike-Leo-Smith** [comment]
> I'm building with in powershell using vsbuild tools. shooul I create another config?

Oh I see. The vsbuild generator is a [multi-config](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html) generator and the `CMAKE_BUILD_TYPE` has no effect.

For multi-config generators, you would need to pass `--config <build-type>` to `cmake --build` to select the build type:
```bash
cmake --build build --config Release
```

**Comment by OmidGhotbi** [comment]
> > I'm building with in powershell using vsbuild tools. shooul I create another config?
> 
> Oh I see. The vsbuild generator is a [multi-config](https://cmake.org/cmake/help/latest/prop_gbl/GENERATOR_IS_MULTI_CONFIG.html) generator and the `CMAKE_BUILD_TYPE` has no effect.
> 
> For multi-config generators, you would need to pass `--config <build-type>` to `cmake --build` to select the build type:
> 
> cmake --build build --config Release

Thank you so much, I think it was implied by default unless I change it to debug. My mistake. Thanks.
